server:
  port: 8084
  read_timeout: 10s
  write_timeout: 10s

backends:
  - url: https://load-balancer-server-ws89.vercel.app
  - url: https://load-balancer-server-bn5kpl8bh.vercel.app

load_balancer:
  algorithm: "round-robin"

health_check:
  interval: 20s
  timeout: 2s
